name: Changeset PR

on:
  pull_request:
    branches: [main]

jobs:
  changeset:
    name: Changeset Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Check for changesets
        run: npm run changeset status

      - name: Validate changesets
        run: npm run changeset version --dry-run
